{"timestamp":"2025-08-26T03:30:00.056Z","model":"errorLog","data":{"id":"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.057Z","model":"errorLog","data":{"id":"f578b4f8-bf02-44ff-9b46-cf94bd61c634","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.058Z","model":"errorLog","data":{"id":"0d812b96-af96-41a1-b335-861e908be1a7","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.063Z","model":"errorLog","data":{"id":"9713f541-32bc-4609-aad5-cf8213f23379","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.064Z","model":"errorLog","data":{"id":"8b20e8b8-d297-4a40-baac-6543d4462a61","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.065Z","model":"errorLog","data":{"id":"be468bd2-ca66-41ee-87f5-edadd2e2edea","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.065Z","model":"errorLog","data":{"id":"012c7de1-9367-412c-9fd4-95d91d63ba61","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.065Z","model":"errorLog","data":{"id":"4588ff66-7529-4078-8bd6-d788b8ddc7fe","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.066Z","model":"errorLog","data":{"id":"ac802141-ef10-48d5-a0dd-cc9f34a041c3","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.066Z","model":"errorLog","data":{"id":"a6ff6f8c-e99b-498c-9698-663265c7c5c8","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.067Z","model":"errorLog","data":{"id":"213a200d-e9cb-4d30-afab-f6b11a989b1d","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.067Z","model":"errorLog","data":{"id":"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.068Z","model":"errorLog","data":{"id":"a2dc306a-f179-460a-8f86-e2006b4b1ed1","message":"ECONNREFUSED","stack":"AggregateError: \n    at internalConnectMultiple (node:net:1139:18)\n    at afterConnectMultiple (node:net:1714:7)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","context":{"service":"CacheService","errorCode":"ECONNREFUSED"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.068Z","model":"errorLog","data":{"id":"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab","message":"retryFailedLogs failed","stack":"SyntaxError: Unexpected token 'I', \"INVALID\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\n    at eval (/workspace/server/cron/index.js:118:7)\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)","context":{"error":"Unexpected token 'I', \"INVALID\" is not valid JSON","taskName":"retry_failed_logs","timestamp":"2025-08-26T04:30:00.012Z"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
{"timestamp":"2025-08-26T03:30:00.069Z","model":"errorLog","data":{"id":"efd5d719-3976-434c-93d1-6a7cea6b9950","message":"Failed to run retryFailedLogs","stack":"SyntaxError: Unexpected token 'I', \"INVALID\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\n    at eval (/workspace/server/cron/index.js:118:7)\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)","context":{"message":"Unexpected token 'I', \"INVALID\" is not valid JSON","duration":36,"timestamp":"2025-08-26T04:30:00.048Z"}},"error":"\nInvalid `client.create()` invocation in\n/workspace/server/utils/logger.js:315:24\n\n  312     await client.create({ data: entry });\n  313   }\n  314 } else {\n→ 315   await client.create({\n          data: [\n            {\n              id: \"6ef6fe19-42e4-4f52-9178-b2e8107e7c9f\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"f578b4f8-bf02-44ff-9b46-cf94bd61c634\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"0d812b96-af96-41a1-b335-861e908be1a7\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"9713f541-32bc-4609-aad5-cf8213f23379\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"8b20e8b8-d297-4a40-baac-6543d4462a61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"be468bd2-ca66-41ee-87f5-edadd2e2edea\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"012c7de1-9367-412c-9fd4-95d91d63ba61\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"4588ff66-7529-4078-8bd6-d788b8ddc7fe\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ac802141-ef10-48d5-a0dd-cc9f34a041c3\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a6ff6f8c-e99b-498c-9698-663265c7c5c8\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"213a200d-e9cb-4d30-afab-f6b11a989b1d\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"ed4ccb7f-f5eb-45f5-a62b-c38b12a6044a\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"a2dc306a-f179-460a-8f86-e2006b4b1ed1\",\n              message: \"ECONNREFUSED\",\n              stack: \"AggregateError: \\n    at internalConnectMultiple (node:net:1139:18)\\n    at afterConnectMultiple (node:net:1714:7)\\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)\",\n              context: {\n                service: \"CacheService\",\n                errorCode: \"ECONNREFUSED\"\n              }\n            },\n            {\n              id: \"e0f5bb92-a4e5-4494-ae53-6fd9c8d6f3ab\",\n              message: \"retryFailedLogs failed\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                error: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                taskName: \"retry_failed_logs\",\n                timestamp: \"2025-08-26T04:30:00.012Z\"\n              }\n            },\n            {\n              id: \"efd5d719-3976-434c-93d1-6a7cea6b9950\",\n              message: \"Failed to run retryFailedLogs\",\n              stack: \"SyntaxError: Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\\n    at JSON.parse (<anonymous>)\\n    at eval (/workspace/server/cron/retryFailedLogs.js:50:35)\\n    at Proxy._transactionWithCallback (/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:722:18)\\n    at retryFailedLogs (/workspace/server/cron/retryFailedLogs.js:25:5)\\n    at eval (/workspace/server/cron/index.js:118:7)\\n    at runJobSafely (/workspace/server/cron/index.js:64:5)\\n    at __vite_ssr_import_0__.default.schedule.scheduled (/workspace/server/cron/index.js:117:5)\\n    at Timeout._onTimeout (/workspace/node_modules/node-cron/src/scheduler/runner.ts:100:30)\",\n              context: {\n                message: \"Unexpected token 'I', \\\"INVALID\\\" is not valid JSON\",\n                duration: 36,\n                timestamp: \"2025-08-26T04:30:00.048Z\"\n              }\n            }\n          ],\n          skipDuplicates: true\n          ~~~~~~~~~~~~~~\n        })\n\nUnknown argument `skipDuplicates`. Available options are marked with ?."}
